/**
 * Enemy and boss sprites (Sweetie 16 palette, see sprites.ts). Most are symmetric and drawn as a
 * left half that is mirrored.
 */
import type { EnemyKind } from '../../types';
import type { Sprite } from './sprites';

function sprite(rows: string[]): Sprite {
  const w = rows[0].length;
  for (const r of rows) if (r.length !== w) throw new Error(`Sprite row width ${r.length} ≠ ${w}: "${r}"`);
  return { w, h: rows.length, rows };
}
const mirrored = (half: string[]) => sprite(half.map((r) => r + [...r].reverse().join('')));

const golem = mirrored([
  '..........',
  '.....kkkkk',
  '....kssssw',
  '....ksssss',
  '....kskaas',
  '....ksssss',
  '..kkkddddd',
  '.kssskkkkk',
  'kssssksssg',
  'ksdssksssl',
  'ksdsskssss',
  'kdddskdsss',
  'kssskksdss',
  '.kkk.ksdss',
  '.....kssss',
  '.....kdkkk',
  '....kssk..',
  '....ksdk..',
  '...kkkkk..',
  '..........',
]);

const bramble = mirrored([
  '........k.',
  '..k....kgk',
  '.kgk..kglg',
  '.kglkkgggg',
  'kgggggtggg',
  'kggtggggtg',
  'kgtggkrrkg',
  'kgggggkkgg',
  'kggtgggggg',
  '.kgggwkwkw',
  '.kggggkkkk',
  'kgtggggggg',
  'kggggtgggt',
  'kgtggggtgg',
  '.kggtggggg',
  '..kkgggkgg',
  '...kgk.kgk',
  '...kok.kok',
  '..kkkk.kkk',
  '..........',
]);

const knight = mirrored([
  '........kr',
  '.......krr',
  '.....kkkkk',
  '....kswsss',
  '....kkkkkk',
  '....ksskkk',
  '....kssssk',
  '.....kdddd',
  '.kkkkkkkkk',
  'kswkyyyyyy',
  'ksskyrrrrr',
  'kdskyrrrry',
  'kdskyrrrry',
  '.kkkyyyyyy',
  '..kkyrrrry',
  '...kyrrrry',
  '...kkyrrry',
  '..kd.kyrry',
  '..kd..kyyy',
  '.kkk...kkk',
]);

const wraith = mirrored([
  '......kkkk',
  '....kknnnn',
  '...knnbbbb',
  '..knbbkkkk',
  '..knbkkakk',
  '..knbkkkkk',
  '.knbbbkkkk',
  '.knbcbbbkk',
  'kobcbbbbbb',
  'knocbbbbbb',
  'knbobbbbbb',
  'knbcobbbbb',
  '.knbcobbbb',
  '.knbcbobbb',
  '..knbbbobb',
  '..knbnbbob',
  '...knbnbbo',
  '....kbnkbn',
  '.....kk.kb',
  '........kk',
]);

const harpy = mirrored([
  '..........',
  '.......kkk',
  '......kooo',
  '......koyy',
  'kk....kyky',
  'kok....kyy',
  'koyk..kkkk',
  'koyyk.kooo',
  '.koyykooyy',
  '.koyyyooyy',
  '..koyyoooy',
  '..kooyoooo',
  '..rkoookoo',
  '...rkkk.ko',
  '........ko',
  '.......kyk',
  '......ky.y',
  '......kk.k',
  '..........',
  '..........',
]);

const ogre = mirrored([
  '..........',
  'kkk.......',
  'kggk..kkkk',
  'kglk.kgggg',
  'kggk.kgrkg',
  'kggk.kgggg',
  'kggk.kwkkk',
  'kgggkkgggg',
  'kggggggsss',
  '.kgggggsss',
  '..kkkkksds',
  '.....ksdss',
  '.....kssds',
  '.....kkkkk',
  '.....kggk.',
  '.....kggk.',
  '.....kggk.',
  '....kkkkk.',
  '..........',
  '..........',
]);

const ram = mirrored([
  '..kkkk....',
  '.kyyyyk...',
  'kyokkyok..',
  'kyk..kyokk',
  'kyok.kokww',
  '.kyykkwwww',
  '..kkkwkrww',
  '.....kwwdd',
  '.....kwdkk',
  '......kddd',
  '..kkkkkkkk',
  '.kwwwwssss',
  'kwwwwkdddd',
  'kwdwkddedd',
  'kddk.kdddd',
  'kyyk.kdddd',
  '.kk..kdkkk',
  '.....kdk..',
  '....kkkk..',
  '..........',
]);

const serpent = mirrored([
  '......kkkk',
  '.....kllll',
  '.....kgykg',
  '.....kgggg',
  '......kggg',
  '.......kgg',
  '.......kgg',
  '.....kkkgg',
  '....kglllg',
  '....kggygg',
  '....kttttt',
  '..kkkkkkkk',
  '.kglllgggg',
  '.kggyggygg',
  '.ktttttttt',
  'kkkkkkkkkk',
  'kglllggggg',
  'kggyggyggg',
  'kttttttttt',
  'kkkkkkkkkk',
]);

const dummy = mirrored([
  '..........',
  '.......kkk',
  '......kyyy',
  '......kyky',
  '......kyyy',
  '........ko',
  '.kkkkkkkkk',
  '.kyyyyyyyy',
  '.kkkkkyyyy',
  '.....kyrrr',
  '.....kyrww',
  '.....kyrrr',
  '.....kyyyy',
  '......kkko',
  '........ko',
  '........ko',
  '........ko',
  '.....kkkkk',
  '..........',
  '..........',
]);

// ── Bosses (24 wide) ─────────────────────────────────────────────────────

const wyrm = mirrored([
  '......k.....',
  '......kk....',
  '.......kk...',
  'k.......kk..',
  'kk.......kkk',
  'kpk.....kkss',
  'kppk...ksssw',
  'kpppk..kssss',
  'kpprpk.ksrks',
  'kprppk.kssss',
  'kprpppkkdsss',
  'kprppppkkdss',
  'kpprppkwkdkk',
  '.kppppkwk.kk',
  '.kpppkkkkkkk',
  '..kppkssddss',
  '..kpkkssdsds',
  '...kksssdsss',
  '....ksdsssds',
  '....kssdssss',
  '.....kkkkkkk',
  '.....kk...kk',
]);

const giant = mirrored([
  '........kkkk',
  '.......kcccc',
  '.......kcykc',
  '.......kcccc',
  '.......kwwww',
  '...kkkkkwwww',
  '..kcaacckwww',
  '.kcaaccccckw',
  'kcaacccccccc',
  'kcacckcccccc',
  'kcacckcccbcc',
  'kcbck.kccbcc',
  'kcbck.kcccbc',
  'kccck.knnnnn',
  'kcck..knnynn',
  '.kkk..kcccck',
  '......kccck.',
  '......kcbck.',
  '......kcbck.',
  '.....kkcbck.',
  '.....kwwwwk.',
  '.....kkkkkk.',
]);

const treant = mirrored([
  '....tt...ttt',
  '..ttggt.tggg',
  '.tgggggtgglg',
  'tgglgggggggg',
  'tggggtgggtgg',
  '.tttkddddddd',
  'k...kdeddddd',
  'dk..kdllkddd',
  'ddk.kddddddd',
  '.ddkkdkkkkdd',
  '..ddkdddddde',
  '...dkdedddde',
  '....kdeddded',
  '....kddeddde',
  '....kdddedde',
  '...kkddddddd',
  '..kekddddddd',
  '.kek.kdddedd',
  'kek...kedeke',
  'ek...ke..kek',
  'k...ke...ke.',
  '....k....k..',
]);

export const CREATURES: Record<EnemyKind, Sprite> = {
  golem,
  bramble,
  knight,
  wraith,
  harpy,
  ogre,
  ram,
  serpent,
  dummy,
  wyrm,
  giant,
  treant,
};
