// Writes dist/sw.js: precaches every built file so the app works fully offline after one visit.
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const dist = 'dist';
const files = [];
(function walk(dir) {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) walk(p);
    else if (f !== 'sw.js') files.push(p);
  }
})(dist);

const hash = createHash('sha256').update(readFileSync('scripts/build-sw.mjs'));
for (const f of files.sort()) hash.update(f).update(readFileSync(f));
const version = hash.digest('hex').slice(0, 12);
const urls = ['/', ...files.map((f) => '/' + relative(dist, f).split('\\').join('/'))];

writeFileSync(
  join(dist, 'sw.js'),
  `// Generated by scripts/build-sw.mjs
const CACHE = 'gym-quest-${version}';
const URLS = ${JSON.stringify(urls)};
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(URLS)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()),
  );
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  // Cache-first everywhere: gyms have bad signal. New versions arrive when sw.js changes.
  if (req.mode === 'navigate') {
    e.respondWith(caches.match('/', { ignoreVary: true }).then((hit) => hit || fetch(req)));
    return;
  }
  e.respondWith(caches.match(req, { ignoreVary: true, ignoreSearch: true }).then((hit) => hit || fetch(req)));
});
`,
);
console.log(`dist/sw.js: ${urls.length} files, cache ${version}`);
